FROM node:20-alpine
LABEL org.opencontainers.image.authors="clvs7 <me@clvs7.com>"

COPY . /app

RUN set -x && \
    apk add --no-cache bash dumb-init git && \
    cd /app/ && \
    git clone --depth=1 https://github.com/clvs7-gh/rec0bot-plugin-sindoi rec0bot/plugins/sindoi && \
    cd rec0bot/plugins/sindoi && \
    # Build sindoi plugin
    npm i && npm run build && \
    npm prune --production && \
    cd ../../ && \
    # Build core
    npm i && npm run build && \
    npm prune --production

WORKDIR /app/rec0bot

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "output/index.js"]
