FROM node:22-alpine
LABEL org.opencontainers.image.authors="clvs7 <me@clvs7.com>"

COPY . /app

RUN set -x && \
    apk add --no-cache bash dumb-init git && \
    cd /app/ && \
    git clone --depth=1 -b v2 https://github.com/clvs7-gh/rec0bot-plugin-sindoi rec0bot/plugins/sindoi && \
    cd rec0bot/plugins/sindoi && npm ci --production && cd - && \
    npm ci --production

WORKDIR /app/rec0bot

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "--experimental-strip-types", "index.ts"]
